/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZhIndexRouteImport } from './routes/zh.index'
import { Route as ZhDownloadRouteImport } from './routes/zh.download'
import { Route as ZhAboutRouteImport } from './routes/zh.about'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalLicenseRouteImport } from './routes/legal/license'
import { Route as LegalDisclaimerRouteImport } from './routes/legal/disclaimer'
import { Route as ZhLegalTermsRouteImport } from './routes/zh.legal.terms'
import { Route as ZhLegalPrivacyRouteImport } from './routes/zh.legal.privacy'
import { Route as ZhLegalLicenseRouteImport } from './routes/zh.legal.license'
import { Route as ZhLegalDisclaimerRouteImport } from './routes/zh.legal.disclaimer'

const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhRoute,
} as any)
const ZhDownloadRoute = ZhDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ZhRoute,
} as any)
const ZhAboutRoute = ZhAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ZhRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalLicenseRoute = LegalLicenseRouteImport.update({
  id: '/legal/license',
  path: '/legal/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLegalTermsRoute = ZhLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => ZhRoute,
} as any)
const ZhLegalPrivacyRoute = ZhLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => ZhRoute,
} as any)
const ZhLegalLicenseRoute = ZhLegalLicenseRouteImport.update({
  id: '/legal/license',
  path: '/legal/license',
  getParentRoute: () => ZhRoute,
} as any)
const ZhLegalDisclaimerRoute = ZhLegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => ZhRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/zh': typeof ZhRouteWithChildren
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/download': typeof ZhDownloadRoute
  '/zh/': typeof ZhIndexRoute
  '/zh/legal/disclaimer': typeof ZhLegalDisclaimerRoute
  '/zh/legal/license': typeof ZhLegalLicenseRoute
  '/zh/legal/privacy': typeof ZhLegalPrivacyRoute
  '/zh/legal/terms': typeof ZhLegalTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/download': typeof ZhDownloadRoute
  '/zh': typeof ZhIndexRoute
  '/zh/legal/disclaimer': typeof ZhLegalDisclaimerRoute
  '/zh/legal/license': typeof ZhLegalLicenseRoute
  '/zh/legal/privacy': typeof ZhLegalPrivacyRoute
  '/zh/legal/terms': typeof ZhLegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/download': typeof DownloadRoute
  '/zh': typeof ZhRouteWithChildren
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/download': typeof ZhDownloadRoute
  '/zh/': typeof ZhIndexRoute
  '/zh/legal/disclaimer': typeof ZhLegalDisclaimerRoute
  '/zh/legal/license': typeof ZhLegalLicenseRoute
  '/zh/legal/privacy': typeof ZhLegalPrivacyRoute
  '/zh/legal/terms': typeof ZhLegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/download'
    | '/zh'
    | '/legal/disclaimer'
    | '/legal/license'
    | '/legal/privacy'
    | '/legal/terms'
    | '/zh/about'
    | '/zh/download'
    | '/zh/'
    | '/zh/legal/disclaimer'
    | '/zh/legal/license'
    | '/zh/legal/privacy'
    | '/zh/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/download'
    | '/legal/disclaimer'
    | '/legal/license'
    | '/legal/privacy'
    | '/legal/terms'
    | '/zh/about'
    | '/zh/download'
    | '/zh'
    | '/zh/legal/disclaimer'
    | '/zh/legal/license'
    | '/zh/legal/privacy'
    | '/zh/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/download'
    | '/zh'
    | '/legal/disclaimer'
    | '/legal/license'
    | '/legal/privacy'
    | '/legal/terms'
    | '/zh/about'
    | '/zh/download'
    | '/zh/'
    | '/zh/legal/disclaimer'
    | '/zh/legal/license'
    | '/zh/legal/privacy'
    | '/zh/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DownloadRoute: typeof DownloadRoute
  ZhRoute: typeof ZhRouteWithChildren
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalLicenseRoute: typeof LegalLicenseRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof ZhRoute
    }
    '/zh/download': {
      id: '/zh/download'
      path: '/download'
      fullPath: '/zh/download'
      preLoaderRoute: typeof ZhDownloadRouteImport
      parentRoute: typeof ZhRoute
    }
    '/zh/about': {
      id: '/zh/about'
      path: '/about'
      fullPath: '/zh/about'
      preLoaderRoute: typeof ZhAboutRouteImport
      parentRoute: typeof ZhRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/license': {
      id: '/legal/license'
      path: '/legal/license'
      fullPath: '/legal/license'
      preLoaderRoute: typeof LegalLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/legal/terms': {
      id: '/zh/legal/terms'
      path: '/legal/terms'
      fullPath: '/zh/legal/terms'
      preLoaderRoute: typeof ZhLegalTermsRouteImport
      parentRoute: typeof ZhRoute
    }
    '/zh/legal/privacy': {
      id: '/zh/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/zh/legal/privacy'
      preLoaderRoute: typeof ZhLegalPrivacyRouteImport
      parentRoute: typeof ZhRoute
    }
    '/zh/legal/license': {
      id: '/zh/legal/license'
      path: '/legal/license'
      fullPath: '/zh/legal/license'
      preLoaderRoute: typeof ZhLegalLicenseRouteImport
      parentRoute: typeof ZhRoute
    }
    '/zh/legal/disclaimer': {
      id: '/zh/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/zh/legal/disclaimer'
      preLoaderRoute: typeof ZhLegalDisclaimerRouteImport
      parentRoute: typeof ZhRoute
    }
  }
}

interface ZhRouteChildren {
  ZhAboutRoute: typeof ZhAboutRoute
  ZhDownloadRoute: typeof ZhDownloadRoute
  ZhIndexRoute: typeof ZhIndexRoute
  ZhLegalDisclaimerRoute: typeof ZhLegalDisclaimerRoute
  ZhLegalLicenseRoute: typeof ZhLegalLicenseRoute
  ZhLegalPrivacyRoute: typeof ZhLegalPrivacyRoute
  ZhLegalTermsRoute: typeof ZhLegalTermsRoute
}

const ZhRouteChildren: ZhRouteChildren = {
  ZhAboutRoute: ZhAboutRoute,
  ZhDownloadRoute: ZhDownloadRoute,
  ZhIndexRoute: ZhIndexRoute,
  ZhLegalDisclaimerRoute: ZhLegalDisclaimerRoute,
  ZhLegalLicenseRoute: ZhLegalLicenseRoute,
  ZhLegalPrivacyRoute: ZhLegalPrivacyRoute,
  ZhLegalTermsRoute: ZhLegalTermsRoute,
}

const ZhRouteWithChildren = ZhRoute._addFileChildren(ZhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DownloadRoute: DownloadRoute,
  ZhRoute: ZhRouteWithChildren,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalLicenseRoute: LegalLicenseRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
